final Map<String, List<String>> keywordFormsMap = {
  "Malware": ["malware", "malicious software", "virus", "worm", "trojan", "adware"],
  "Cyber Security": ["Cyber Security","CyberSecurity","Cyber-Security"],
  "Phishing": ["phishing", "email scam", "fake websites", "social engineering attack", "spear phishing", "phishing email", "phishing","fishing"],
  "Ransomware": ["ransomware", "file locking virus", "crypto-ransomware", "locker ransomware", "data encryption virus", "ransomware"],
  "Password Security": ["password security", "password protection", "strong passwords", "password safety", "password strength", "passwordsecurity"],
  "Password Manager": ["password manager", "password vault", "credential manager", "password storage", "secure password keeper", "passwordmanager"],
  "Encryption": ["encryption", "data encryption", "cryptography", "encrypted communication", "secure data transfer", "encryption", "encrypt"],
  "Two-Factor Authentication": ["two-factor authentication", "2fa", "multi-factor authentication", "2-step verification", "two step authentication", "factor authentication"],
  "Firewall": ["firewall", "network firewall", "web application firewall", "packet filtering firewall", "host-based firewall", "firewall"],
  "VPN": ["vpn (virtual private network)", "vpn", "virtual private network", "secure connection", "encrypted tunnel", "virtual network", "private network"],
  "Social Engineering": ["social engineering", "psychological manipulation", "human hacking", "social attack", "social engineering scam", "social engineering"],
  "Data Breach": ["data breach", "information leak", "security breach", "data exposure", "breach data"],
  "Botnet": ["botnet", "zombie network", "ddos botnet", "malicious botnet", "command and control botnet", "botnet"],
  "Spyware": ["spyware", "spying software", "surveillance software", "tracking software", "malicious tracking", "spyware"],
  "Zero-Day Attack": ["zero-day attack", "zero-day exploit", "zero-day vulnerability", "undisclosed exploit", "zero-day threat", "zero day attack"],
  "Man-in-the-Middle Attack": ["man-in-the-middle attack", "mitm attack", "eavesdropping attack", "session hijacking", "network interception", "middle of attack"],
  "Antivirus": ["antivirus", "anti-malware", "virus protection", "anti-virus software", "security software", "anti-virus"],
  "Network Security": ["network security", "secure network", "network protection", "cybersecurity for networks", "network defense", "network security"],
  "DDOS attack": ["ddos (distributed denial-of-service) attack", "ddos attack", "distributed denial of service", "denial-of-service attack", "traffic flooding attack", "distributed denial-of-service", "ddos"],
  "IDS": ["intrusion detection system (ids)", "ids", "intrusion detection", "network intrusion detection", "security monitoring", "intrusion detection system"],
  "Cyberattack": ["cyberattack", "cyber assault", "digital attack", "online attack", "cyber offensive", "cyberattack"],
  "Data Leakage": ["data leakage", "information leakage", "data loss", "information loss", "data exposure", "data", "leakage"],
  "Cyber Espionage": ["cyber espionage", "digital espionage", "hacking for spying", "cyber surveillance", "online espionage", "espionage"],
  "Cloud Security": ["cloud security", "cloud data protection", "cloud computing security", "securing cloud storage", "cloud-based security", "cloud", "security"],
  "Secure Browsing": ["secure browsing", "safe browsing", "browser security", "online security", "private browsing", "secure", "browsing"],
  "Cyber Hygiene": ["cyber hygiene", "digital hygiene", "security best practices", "online hygiene", "cybersecurity hygiene", "hygiene"],
  "Incident Response": ["incident response", "security incident handling", "cyber incident response", "breach response", "incident management", "incident", "response"],
  "Cyber Defense": ["cyber defense", "digital defense", "online protection", "cybersecurity defense", "cybersecurity protection", "defense"],
  "Digital Forensics": ["digital forensics", "cyber forensics", "computer forensics", "forensic investigation", "digital crime investigation", "digital", "forensics"],
  "Security Patch": ["security patch", "software patch", "vulnerability patch", "patch update", "critical security fix", "security", "patch"],
  "Vulnerability": ["vulnerability", "security vulnerability", "system weakness", "exploitable weakness", "software vulnerability", "vulnerability"],
  "Threat Intelligence": ["threat intelligence", "cyber threat intelligence", "security intelligence", "cyber intelligence", "threat information", "threat", "intelligence"],
  "Access Control": ["access control", "identity access management", "access rights", "user permissions", "access restrictions", "access", "control"],
  "Security Audit": ["security audit", "cybersecurity audit", "system audit", "network audit", "security assessment", "security", "audit"],
  "Identity Theft": ["identity theft", "id theft", "personal data theft", "identity fraud", "information theft", "identity", "theft"],
  "Privacy Protection": ["privacy protection", "data privacy", "personal data protection", "online privacy", "information privacy", "privacy", "protection"],
  "Application Security": ["application security", "app security", "software security", "web application security", "code security", "application", "security"],
  "Network Monitoring": ["network monitoring", "network surveillance", "network traffic monitoring", "real-time network monitoring", "network watch", "network", "monitoring"],
  "Cyber Risk Management": ["cyber risk management", "digital risk management", "cybersecurity risk management", "it risk management", "risk assessment", "cyber risk"],
  "Endpoint Security": ["endpoint security", "device security", "endpoint protection", "secure endpoints", "endpoint defense", "endpoint security"],
  "Security Token": ["security token", "authentication token", "digital token", "tokenized security", "two-factor authentication token", "security", "token"],
  "Provider": ["provider", "flutter provider", "state management", "change notifier", "consumer widget", "provider"],
  "Hello": ["hello", "hi", "yo", "assalam", "assalam o alaikum", "salam", "hey", "assalamoalaikum"],
  "You": ["you",],
  "Your": ["yours", "your"],
  "MySQL": ["sql", "mysql"]
};