Map<String, List<String>> singularPluralMap = {
  // Keywords Singular and plural

  // verbs
  "is": ["are"],
  "was": ["were"],
  "use" : ["uses"],

  // Words with Singular and Plural Forms
  "basic": ["basics"],
  "detect": ["detects"],
  "malware": ["malware"], // no plural form
  "phishing": ["phishings"],
  "ransomware": ["ransomware"], // no plural form
  "password security": ["password securities"],
  "password manager": ["password managers"],
  "encryption": ["encrypted files"], // conceptual pluralization
  "two-factor authentication": ["two-factor authentications"],
  "firewall": ["firewalls"],
  "vpn (virtual private network)": ["vpns (virtual private networks)"],
  "social engineering": ["social engineerings"],
  "data breach": ["data breaches"],
  "botnet": ["botnets"],
  "spyware": ["spywares"],
  "zero-day attack": ["zero-day attacks"],
  "man-in-the-middle attack": ["man-in-the-middle attacks"],
  "antivirus": ["antiviruses"],
  "network security": ["network securities"],
  "ddos (distributed denial-of-service) attack": ["ddos attacks"],
  "intrusion detection system (ids)": ["intrusion detection systems (ids)"],
  "cyberattack": ["cyberattacks"],
  "data leakage": ["data leaks"],
  "cyber espionage": ["cyber espionages"],
  "cloud security": ["cloud securities"],
  "secure browsing": ["secure browsings"],
  "cyber hygiene": ["cyber hygienes"],
  "incident response": ["incident responses"],
  "cyber defense": ["cyber defenses"],
  "digital forensics": ["digital forensic studies"],
  "security patch": ["security patches"],
  "vulnerability": ["vulnerabilities"],
  "threat intelligence": ["threat intelligences"],
  "access control": ["access controls"],
  "security audit": ["security audits"],
  "identity theft": ["identity thefts"],
  "privacy protection": ["privacy protections"],
  "application security": ["application securities"],
  "network monitoring": ["network monitorings"],
  "cyber risk management": ["cyber risk managements"],
  "endpoint security": ["endpoint securities"],
  "security token": ["security tokens"],
  // Regular plurals
  "cat": ["cats"],
  "dog": ["dogs"],
  "book": ["books"],
  "apple": ["apples"],
  "car": ["cars"],
  "computer": ["computers"],
  "tree": ["trees"],
  "city": ["cities"],
  "bus": ["buses"],
  "table": ["tables"],
  "chair": ["chairs"],
  "house": ["houses"],
  "window": ["windows"],
  "bottle": ["bottles"],
  "pen": ["pens"],
  "shirt": ["shirts"],
  "shoe": ["shoes"],
  "phone": ["phones"],
  "ball": ["balls"],
  "cup": ["cups"],
  "sock": ["socks"],
  "key": ["keys"],
  "clock": ["clocks"],
  "lamp": ["lamps"],
  "hat": ["hats"],
  "bag": ["bags"],
  "ticket": ["tickets"],
  "watch": ["watches"],
  "box": ["boxes"],
  "brush": ["brushes"],
  "fork": ["forks"],
  "spoon": ["spoons"],
  "plate": ["plates"],
  "glass": ["glasses"],
  "pencil": ["pencils"],
  "notebook": ["notebooks"],
  "paper": ["papers"],
  "pants": ["pants"], // Same form for singular and plural
  "hair": ["hairs"], // Though used in both singular and plural
  "door": ["doors"],
  "road": ["roads"],
  "street": ["streets"],
  "mountain": ["mountains"],
  "river": ["rivers"],
  "lake": ["lakes"],
  "ocean": ["oceans"],
  "country": ["countries"],
  "state": ["states"],
  "region": ["regions"],
  "company": ["companies"],
  "team": ["teams"],
  "town": ["towns"],
  "village": ["villages"],
  "vowel": ["vowels"],
  "consonant": ["consonants"],
  "idea": ["ideas"],
  "thought": ["thoughts"],
  "plan": ["plans"],
  "project": ["projects"],
  "task": ["tasks"],
  "goal": ["goals"],
  "game": ["games"],
  "match": ["matches"],
  "contest": ["contests"],
  "question": ["questions"],
  "answer": ["answers"],
  "problem": ["problems"],
  "solution": ["solutions"],
  "challenge": ["challenges"],
  "opportunity": ["opportunities"],
  "decision": ["decisions"],
  "method": ["methods"],
  "exercise": ["exercises"],
  "test": ["tests"],
  "practice": ["practices"],
  "celebration": ["celebrations"],
  "event": ["events"],
  "holiday": ["holidays"],
  "festival": ["festivals"],
  "tradition": ["traditions"],
  "custom": ["customs"],
  "symbol": ["symbols"],
  "sign": ["signs"],
  "signal": ["signals"],
  "information": ["informations"], // Though it's usually uncountable, it can be used in plural context
  "communication": ["communications"],
  "equipment": ["equipment"], // Uncountable, remains same in plural
  "furniture": ["furniture"], // Uncountable, remains same in plural
  "money": ["moneys"], // Uncommon, but plural form exists
  "advice": ["advices"], // Uncommon, but plural form exists
  "news": ["news"], // Unchanged in plural
  "homework": ["homeworks"], // Sometimes used in plural context
  "work": ["works"], // Sometimes used in plural context
  "art": ["arts"], // Rare, but plural form exists
  "literature": ["literature"], // Unchanged in plural
  "science": ["sciences"],
  "language": ["languages"],
  "knowledge": ["knowledge"], // Unchanged in plural
  "student": ["students"],
  "teacher": ["teachers"],
  "scientist": ["scientists"],
  "engineer": ["engineers"],
  "doctor": ["doctors"],
  "nurse": ["nurses"],
  "player": ["players"],
  "athlete": ["athletes"],
  "artist": ["artists"],
  "musician": ["musicians"],
  "writer": ["writers"],
  "author": ["authors"],
  "director": ["directors"],
  "producer": ["producers"],
  "actor": ["actors"],
  "actress": ["actresses"],
  "model": ["models"],
  "leader": ["leaders"],
  "entrepreneur": ["entrepreneurs"],

  // Irregular Plurals
  "man": ["men"],
  "woman": ["women"],
  "child": ["children"],
  "foot": ["feet"],
  "tooth": ["teeth"],
  "mouse": ["mice"],
  "goose": ["geese"],
  "leaf": ["leaves"],
  "knife": ["knives"],
  "wife": ["wives"],
  "cactus": ["cacti"],
  "fungus": ["fungi"],
  "bacterium": ["bacteria"],
  "alumnus": ["alumni"],
  "analysis": ["analyses"],
  "criterion": ["criteria"],
  "medium": ["media"],
  "focus": ["foci"],
  "radius": ["radii"],
  "datum": ["data"],
  "thesis": ["theses"],
  "appendix": ["appendices"],
  "index": ["indices"],
  "matrix": ["matrices"],
  "axis": ["axes"],
  "genus": ["genera"],
  "person": ["people"],
  "die": ["dice"],
  "crisis": ["crises"],
  "oasis": ["oases"],
  "quiz": ["quizzes"],
  "fox": ["foxes"],
  "buzz": ["buzzes"],
  "tax": ["taxes"],
  "flesh": ["flesh"], // stays the same in plural
  // Words with multiple plural forms
  "ox": ["oxen", "oxes"], // Both plural forms are acceptable

  // Words that remain the same in both singular and plural
  "sheep": ["sheep"],
  "deer": ["deer"],
  "fish": ["fish"],
  "species": ["species"],
  "series": ["series"],


  // Add more entries as needed
};
